#!/bin/bash

# Script to check and fix Docker deployment on production
echo "🔍 Checking Production Docker Deployment"
echo "========================================"

# Check current version from API
echo "📦 Current production version:"
curl -s http://65.21.4.236:8082/api/version 2>/dev/null || echo "API not accessible"
echo ""

# Instructions for production server
echo "📋 Run these commands on your production server (65.21.4.236):"
echo ""
echo "# 1. SSH into server"
echo "ssh ubuntu@65.21.4.236"
echo ""
echo "# 2. Navigate to project"
echo "cd /opt/shop-management/shop-management-system"
echo ""
echo "# 3. Check current git commit"
echo "git log --oneline -1"
echo ""
echo "# 4. Pull latest code"
echo "git fetch origin"
echo "git reset --hard origin/main"
echo ""
echo "# 5. Check Docker images"
echo "docker images | grep -E '(shop|nammaooru)'"
echo ""
echo "# 6. Stop containers"
echo "docker-compose down"
echo ""
echo "# 7. Remove the old images (IMPORTANT!)"
echo "docker rmi shop-management-system-backend shop-management-system-frontend"
echo ""
echo "# 8. Rebuild with latest code"
echo "docker-compose up --build -d"
echo ""
echo "# 9. Wait and check logs"
echo "sleep 30"
echo "docker logs nammaooru-backend --tail 20"
echo ""
echo "# 10. Verify version"
echo "curl http://localhost:8082/api/version"