#!/bin/bash
echo "=== SHOP MANAGEMENT SYSTEM DIAGNOSTICS ==="
echo "Timestamp: $(date)"
echo ""

echo "1. DOCKER CONTAINERS STATUS:"
docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" 2>/dev/null || echo "Docker not running or no containers"
echo ""

echo "2. ALL CONTAINERS (including stopped):"
docker ps -a --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" 2>/dev/null || echo "Docker not available"
echo ""

echo "3. LISTENING PORTS:"
ss -tlnp | grep -E ':80|:8082|:5432|:6379' || echo "No target ports listening"
echo ""

echo "4. FIREWALL STATUS (if ufw):"
ufw status 2>/dev/null || echo "UFW not available/installed"
echo ""

echo "5. IPTABLES RULES:"
iptables -L INPUT -n 2>/dev/null | grep -E '80|8082' || echo "No iptables rules for ports 80/8082"
echo ""

echo "6. NETWORK CONNECTIVITY TESTS:"
echo "Testing localhost:80..."
curl -I http://localhost 2>&1 | head -3 || echo "localhost:80 failed"
echo ""
echo "Testing localhost:8082..."
curl -I http://localhost:8082 2>&1 | head -3 || echo "localhost:8082 failed"
echo ""
echo "Testing external IP..."
curl -I http://65.21.4.236 2>&1 | head -3 || echo "External IP failed"
echo ""

echo "7. DOCKER LOGS (last 10 lines each):"
echo "--- Frontend logs ---"
docker logs --tail 10 shop-frontend 2>/dev/null || echo "No frontend container"
echo ""
echo "--- Backend logs ---"
docker logs --tail 10 shop-backend 2>/dev/null || echo "No backend container"
echo ""

echo "8. SYSTEM RESOURCES:"
echo "Disk usage:"
df -h / 2>/dev/null || echo "Disk info unavailable"
echo ""
echo "Memory usage:"
free -h 2>/dev/null || echo "Memory info unavailable"
echo ""

echo "=== END DIAGNOSTICS ==="
echo ""
echo "NEXT STEPS:"
echo "1. If containers are not running: Check Docker logs"
echo "2. If ports not listening: Check container port bindings"
echo "3. If localhost works but external doesn't: Check firewall settings"
echo "4. For Hetzner Cloud: Check Security Groups in Cloud Console"
echo "5. For Hetzner Dedicated: Check iptables/firewall configuration"