services:
  # Spring Boot Backend (using locally built JAR)
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.local
    container_name: nammaooru-backend
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-production}
      - DB_URL=${DB_URL:-jdbc:postgresql://host.docker.internal:5432/shop_management_db}
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-admin}
      - JWT_SECRET=${JWT_SECRET:-mySecretKey123456789012345678901234567890}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-86400000}
      - FILE_UPLOAD_PATH=/app/uploads
      - APP_UPLOAD_DIR=/app/uploads
      - PRODUCT_IMAGES_PATH=products
      - MAIL_HOST=${MAIL_HOST:-smtp.gmail.com}
      - MAIL_PORT=${MAIL_PORT:-587}
      - MAIL_USERNAME=${MAIL_USERNAME:-noreplaynammaoorudelivery@gmail.com}
      - MAIL_PASSWORD=${MAIL_PASSWORD:-your-app-password}
      - APP_CORS_ALLOWED_ORIGINS=http://localhost,http://localhost:80
      - APP_CORS_ALLOWED_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - APP_CORS_ALLOWED_HEADERS=*
      - APP_CORS_ALLOW_CREDENTIALS=true
    ports:
      - "0.0.0.0:8082:8080"
    volumes:
      - D:/AAWS/nammaooru/uploads:/app/uploads
    networks:
      - shop-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Angular Frontend (using locally built dist)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    container_name: nammaooru-frontend
    ports:
      - "80:80"
    networks:
      - shop-network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  shop-network:
    driver: bridge