version: '3.8'

services:
  # Spring Boot Backend
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: shop-backend-prod
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      # Connect to PostgreSQL on host (not in Docker)
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/shop_management_db
      - SPRING_DATASOURCE_USERNAME=shopuser
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - FILE_UPLOAD_PATH=/app/uploads
      - APP_CORS_ALLOWED_ORIGINS=https://yourdomain.com
    ports:
      - "8082:8082"
    volumes:
      # Map to Hetzner server photo storage folder
      - /opt/shop-uploads:/app/uploads
      - /var/log/shop-management:/app/logs
    networks:
      - shop-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Angular Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: shop-frontend-prod
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - shop-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: shop-redis-prod
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - shop-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

networks:
  shop-network:
    driver: bridge