-- SQL Script to Update All Product Display Orders
-- Generated from Grocery_App_Final_Order_With_Images.xlsx
-- Total products: 722

UPDATE shop_products SET display_order = 1 WHERE custom_name = 'Onion Big 1kg';
UPDATE shop_products SET display_order = 2 WHERE custom_name = 'Onion Big 2kg';
UPDATE shop_products SET display_order = 3 WHERE custom_name = 'Onion Big 5kg';
UPDATE shop_products SET display_order = 4 WHERE custom_name = 'Onion Small (Sambar Onion) 500g';
UPDATE shop_products SET display_order = 5 WHERE custom_name = 'Shallots (Small Onion) 1kg';
UPDATE shop_products SET display_order = 6 WHERE custom_name = 'Small Onions (Sambhar) 1kg';
UPDATE shop_products SET display_order = 7 WHERE custom_name = 'Tomato Desi 500g';
UPDATE shop_products SET display_order = 8 WHERE custom_name = 'Cherry Tomato 250g';
UPDATE shop_products SET display_order = 9 WHERE custom_name = 'Desi Tomato (Nattu Thakkali) 1kg';
UPDATE shop_products SET display_order = 10 WHERE custom_name = 'Tomato Hybrid 500g';
UPDATE shop_products SET display_order = 11 WHERE custom_name = 'Tomato Hybrid 1kg';
UPDATE shop_products SET display_order = 12 WHERE custom_name = 'Tomato Desi 2kg';
UPDATE shop_products SET display_order = 13 WHERE custom_name = 'Potato 1kg';
UPDATE shop_products SET display_order = 14 WHERE custom_name = 'Sweet Potato 500g';
UPDATE shop_products SET display_order = 15 WHERE custom_name = 'Potato 2kg';
UPDATE shop_products SET display_order = 16 WHERE custom_name = 'Sweet Potato White 500g';
UPDATE shop_products SET display_order = 17 WHERE custom_name = 'Garlic Desi (Small) 250g';
UPDATE shop_products SET display_order = 18 WHERE custom_name = 'Garlic Desi (Small) 500g';
UPDATE shop_products SET display_order = 19 WHERE custom_name = 'Ginger 100g';
UPDATE shop_products SET display_order = 20 WHERE custom_name = 'Ginger Fresh 250g';
UPDATE shop_products SET display_order = 21 WHERE custom_name = 'Ginger 500g';
UPDATE shop_products SET display_order = 22 WHERE custom_name = 'Green Chilli Standard 100g';
UPDATE shop_products SET display_order = 23 WHERE custom_name = 'Green Chilli Long Thin 100g';
UPDATE shop_products SET display_order = 24 WHERE custom_name = 'Green Chilli Standard 250g';
UPDATE shop_products SET display_order = 25 WHERE custom_name = 'Green Chilli Standard 500g';
UPDATE shop_products SET display_order = 26 WHERE custom_name = 'Carrot 250g';
UPDATE shop_products SET display_order = 27 WHERE custom_name = 'Red Carrot 500g';
UPDATE shop_products SET display_order = 28 WHERE custom_name = 'Carrot 500g';
UPDATE shop_products SET display_order = 29 WHERE custom_name = 'Carrot 1kg';
UPDATE shop_products SET display_order = 30 WHERE custom_name = 'Cluster Beans (Kothavarangai) 250g';
UPDATE shop_products SET display_order = 31 WHERE custom_name = 'Snake Beans 250g';
UPDATE shop_products SET display_order = 32 WHERE custom_name = 'Cluster Beans (Guar) 500g';
UPDATE shop_products SET display_order = 33 WHERE custom_name = 'Green Beans 250g';
UPDATE shop_products SET display_order = 34 WHERE custom_name = 'Broad Beans (Avarakkai) 500g';
UPDATE shop_products SET display_order = 35 WHERE custom_name = 'White Beans (Mochai Kottai) 250g';
UPDATE shop_products SET display_order = 36 WHERE custom_name = 'Broad Beans (Flat) 500g';
UPDATE shop_products SET display_order = 37 WHERE custom_name = 'Okra (Ladies Finger) 250g';
UPDATE shop_products SET display_order = 38 WHERE custom_name = 'Ladies Finger 500g';
UPDATE shop_products SET display_order = 39 WHERE custom_name = 'Okra (Ladies Finger) 1kg';
UPDATE shop_products SET display_order = 40 WHERE custom_name = 'Brinjal Green Long 500g';
UPDATE shop_products SET display_order = 41 WHERE custom_name = 'Long Brinjal Purple 500g';
UPDATE shop_products SET display_order = 42 WHERE custom_name = 'Small White Brinjal 250g';
UPDATE shop_products SET display_order = 43 WHERE custom_name = 'Brinjal Purple Round 500g';
UPDATE shop_products SET display_order = 44 WHERE custom_name = 'Brinjal Green Long 1kg';
UPDATE shop_products SET display_order = 45 WHERE custom_name = 'Cabbage 1 Piece (Approx 750g)';
UPDATE shop_products SET display_order = 46 WHERE custom_name = 'Red Cabbage 500g';
UPDATE shop_products SET display_order = 47 WHERE custom_name = 'Cabbage 500g';
UPDATE shop_products SET display_order = 48 WHERE custom_name = 'Cauliflower 1 Piece (Approx 500g)';
UPDATE shop_products SET display_order = 49 WHERE custom_name = 'Cauliflower Florets 200g Pack';
UPDATE shop_products SET display_order = 50 WHERE custom_name = 'Cauliflower 1kg';
UPDATE shop_products SET display_order = 51 WHERE custom_name = 'Drumstick 3 Pieces (Approx 250g)';
UPDATE shop_products SET display_order = 52 WHERE custom_name = 'Drumstick 500g';
UPDATE shop_products SET display_order = 53 WHERE custom_name = 'Drumstick 6 Pieces';
UPDATE shop_products SET display_order = 54 WHERE custom_name = 'Cucumber Salad 500g';
UPDATE shop_products SET display_order = 55 WHERE custom_name = 'Cucumber Madras (Vellari) 500g';
UPDATE shop_products SET display_order = 56 WHERE custom_name = 'Cucumber Desi (Kattu) 500g';
UPDATE shop_products SET display_order = 57 WHERE custom_name = 'Bitter Gourd 250g';
UPDATE shop_products SET display_order = 58 WHERE custom_name = 'Bitter Gourd 500g';
UPDATE shop_products SET display_order = 59 WHERE custom_name = 'Bottle Gourd 500g';
UPDATE shop_products SET display_order = 60 WHERE custom_name = 'Ridge Gourd 500g';
UPDATE shop_products SET display_order = 61 WHERE custom_name = 'Ridge Gourd 1kg';
UPDATE shop_products SET display_order = 62 WHERE custom_name = 'Snake Gourd 500g';
UPDATE shop_products SET display_order = 63 WHERE custom_name = 'Snake Gourd 1kg';
UPDATE shop_products SET display_order = 64 WHERE custom_name = 'Pumpkin Yellow 500g';
UPDATE shop_products SET display_order = 65 WHERE custom_name = 'Pumpkin Red 1kg';
UPDATE shop_products SET display_order = 66 WHERE custom_name = 'White Pumpkin 1kg';
UPDATE shop_products SET display_order = 67 WHERE custom_name = 'Green Peas Fresh 250g';
UPDATE shop_products SET display_order = 68 WHERE custom_name = 'Beetroot 500g';
UPDATE shop_products SET display_order = 69 WHERE custom_name = 'White Radish 500g';
UPDATE shop_products SET display_order = 70 WHERE custom_name = 'Capsicum Green 250g';
UPDATE shop_products SET display_order = 71 WHERE custom_name = 'Mushroom Button Pack 200g';
UPDATE shop_products SET display_order = 72 WHERE custom_name = 'Sweet Corn (Loose) 2 Pcs';
UPDATE shop_products SET display_order = 73 WHERE custom_name = 'Banana Raw (Vazhakkai) 500g';
UPDATE shop_products SET display_order = 74 WHERE custom_name = 'Papaya Raw 1 Piece (Approx 750g)';
UPDATE shop_products SET display_order = 75 WHERE custom_name = 'Tapioca (Kappa) 1kg';
UPDATE shop_products SET display_order = 76 WHERE custom_name = 'Chow Chow (Chayote) 500g';
UPDATE shop_products SET display_order = 77 WHERE custom_name = 'White Onion 500g';
UPDATE shop_products SET display_order = 78 WHERE custom_name = 'Ash Gourd (Vellai Poosanikai) 1kg';
UPDATE shop_products SET display_order = 79 WHERE custom_name = 'Yam (Senai Kizhangu) 500g';
UPDATE shop_products SET display_order = 80 WHERE custom_name = 'Colocasia (Seppankizhangu) 250g';
UPDATE shop_products SET display_order = 81 WHERE custom_name = 'Chillies Red (Ripe) 50g';
UPDATE shop_products SET display_order = 82 WHERE custom_name = 'Yellow Zucchini 500g';
UPDATE shop_products SET display_order = 83 WHERE custom_name = 'Broccoli 500g';
UPDATE shop_products SET display_order = 84 WHERE custom_name = 'Asparagus 250g';
UPDATE shop_products SET display_order = 85 WHERE custom_name = 'Iceberg Lettuce 1 Piece';
UPDATE shop_products SET display_order = 86 WHERE custom_name = 'Celery 1 Bunch';
UPDATE shop_products SET display_order = 87 WHERE custom_name = 'Green Zucchini 500g';
UPDATE shop_products SET display_order = 88 WHERE custom_name = 'Parsnip 500g';
UPDATE shop_products SET display_order = 89 WHERE custom_name = 'Spring Onion 1 Bunch';
UPDATE shop_products SET display_order = 90 WHERE custom_name = 'Leek 500g';
UPDATE shop_products SET display_order = 91 WHERE custom_name = 'Lettuce Green 1 Piece';
UPDATE shop_products SET display_order = 92 WHERE custom_name = 'Water Chestnut 250g';
UPDATE shop_products SET display_order = 93 WHERE custom_name = 'Yam (Karunai Kizhangu) 500g';
UPDATE shop_products SET display_order = 94 WHERE custom_name = 'Baby Corn 200g Pack';
UPDATE shop_products SET display_order = 95 WHERE custom_name = 'Kohlrabi (Noolkol) 500g';
UPDATE shop_products SET display_order = 96 WHERE custom_name = 'Taro Root (Arbi) 500g';
UPDATE shop_products SET display_order = 97 WHERE custom_name = 'Red Capsicum 250g';
UPDATE shop_products SET display_order = 98 WHERE custom_name = 'Yellow Capsicum 250g';
UPDATE shop_products SET display_order = 99 WHERE custom_name = 'Snow Peas 250g';
UPDATE shop_products SET display_order = 100 WHERE custom_name = 'Tindora (Kovakkai) 250g';
UPDATE shop_products SET display_order = 101 WHERE custom_name = 'Banana Flower (Vazhaipoo) 1 Piece';
UPDATE shop_products SET display_order = 102 WHERE custom_name = 'Banana Stem (Vazhaithandu) 1 Piece';
UPDATE shop_products SET display_order = 103 WHERE custom_name = 'Broccoli Florets 200g Pack';
UPDATE shop_products SET display_order = 104 WHERE custom_name = 'Green Banana (Monthan) 500g';
UPDATE shop_products SET display_order = 105 WHERE custom_name = 'Mushroom Oysters 200g';
UPDATE shop_products SET display_order = 106 WHERE custom_name = 'Turmeric Fresh Root 100g';
UPDATE shop_products SET display_order = 107 WHERE custom_name = 'Kohlrabi (German Turnip) 250g';
UPDATE shop_products SET display_order = 108 WHERE custom_name = 'Radish Red 250g';
UPDATE shop_products SET display_order = 109 WHERE custom_name = 'Green Capsicum 500g';
UPDATE shop_products SET display_order = 110 WHERE custom_name = 'Beetroot 1kg';
UPDATE shop_products SET display_order = 111 WHERE custom_name = 'Banana Robusta 500g (Approx 4 Pcs)';
UPDATE shop_products SET display_order = 112 WHERE custom_name = 'Green Banana (Yelakki) 500g';
UPDATE shop_products SET display_order = 113 WHERE custom_name = 'Banana Nendran 500g';
UPDATE shop_products SET display_order = 114 WHERE custom_name = 'Red Banana 4 Pcs';
UPDATE shop_products SET display_order = 115 WHERE custom_name = 'Banana Robusta 1kg';
UPDATE shop_products SET display_order = 116 WHERE custom_name = 'Banana Nendran 1kg';
UPDATE shop_products SET display_order = 117 WHERE custom_name = 'Apple Red Delicious 500g (Approx 3 Pcs)';
UPDATE shop_products SET display_order = 118 WHERE custom_name = 'Pineapple 1 Piece (Approx 1.2kg)';
UPDATE shop_products SET display_order = 119 WHERE custom_name = 'Green Apple 500g';
UPDATE shop_products SET display_order = 120 WHERE custom_name = 'Custard Apple (Sitapazham) 500g';
UPDATE shop_products SET display_order = 121 WHERE custom_name = 'Pineapple Slices Canned 400g';
UPDATE shop_products SET display_order = 122 WHERE custom_name = 'Apple Red Delicious 1kg';
UPDATE shop_products SET display_order = 123 WHERE custom_name = 'Orange Seedless 500g';
UPDATE shop_products SET display_order = 124 WHERE custom_name = 'Orange Seedless 1kg';
UPDATE shop_products SET display_order = 125 WHERE custom_name = 'Mango Standard (Seasonal) 1kg';
UPDATE shop_products SET display_order = 126 WHERE custom_name = 'Grapes Black Seedless 250g';
UPDATE shop_products SET display_order = 127 WHERE custom_name = 'Grapes Green Seedless 500g';
UPDATE shop_products SET display_order = 128 WHERE custom_name = 'Pomegranate 500g (Approx 2 Pcs)';
UPDATE shop_products SET display_order = 129 WHERE custom_name = 'Pomegranate 1kg';
UPDATE shop_products SET display_order = 130 WHERE custom_name = 'Papaya Ripe 1 Piece (Approx 1kg)';
UPDATE shop_products SET display_order = 131 WHERE custom_name = 'Watermelon 1 Piece (Approx 2kg)';
UPDATE shop_products SET display_order = 132 WHERE custom_name = 'Watermelon Cubes 200g Pack';
UPDATE shop_products SET display_order = 133 WHERE custom_name = 'Lemon 4 Pieces (Approx 150g)';
UPDATE shop_products SET display_order = 134 WHERE custom_name = 'Lemon 8 Pieces';
UPDATE shop_products SET display_order = 135 WHERE custom_name = 'Lemon 12 Pieces';
UPDATE shop_products SET display_order = 136 WHERE custom_name = 'Cashew Nut Whole 100g';
UPDATE shop_products SET display_order = 137 WHERE custom_name = 'Almonds 100g';
UPDATE shop_products SET display_order = 138 WHERE custom_name = 'Raisins Black 100g';
UPDATE shop_products SET display_order = 139 WHERE custom_name = 'Pistachio Roasted Salted 50g';
UPDATE shop_products SET display_order = 140 WHERE custom_name = 'Cashew Nut Broken 100g';
UPDATE shop_products SET display_order = 141 WHERE custom_name = 'Pistachio Unsalted 100g';
UPDATE shop_products SET display_order = 142 WHERE custom_name = 'Dried Dates (Kharjuram) 250g';
UPDATE shop_products SET display_order = 143 WHERE custom_name = 'Cashew Nut Split 100g';
UPDATE shop_products SET display_order = 144 WHERE custom_name = 'Raisins Green 100g';
UPDATE shop_products SET display_order = 145 WHERE custom_name = 'Cashew Nut Whole 500g';
UPDATE shop_products SET display_order = 146 WHERE custom_name = 'Almonds 500g';
UPDATE shop_products SET display_order = 147 WHERE custom_name = 'Raisins Black 250g';
UPDATE shop_products SET display_order = 148 WHERE custom_name = 'Dry Fruits Mixed 200g';
UPDATE shop_products SET display_order = 149 WHERE custom_name = 'Apricots Dried 100g';
UPDATE shop_products SET display_order = 150 WHERE custom_name = 'Cashew Nut Broken 250g';
UPDATE shop_products SET display_order = 151 WHERE custom_name = 'Pistachio Roasted Salted 100g';
UPDATE shop_products SET display_order = 152 WHERE custom_name = 'Amla (Indian Gooseberry) 100g';
UPDATE shop_products SET display_order = 153 WHERE custom_name = 'Guava 500g (Approx 3 Pcs)';
UPDATE shop_products SET display_order = 154 WHERE custom_name = 'Starfruit 250g';
UPDATE shop_products SET display_order = 155 WHERE custom_name = 'Kiwi Fruit (Pkt of 3)';
UPDATE shop_products SET display_order = 156 WHERE custom_name = 'Plum 250g';
UPDATE shop_products SET display_order = 157 WHERE custom_name = 'Sapota (Chikku) 500g';
UPDATE shop_products SET display_order = 158 WHERE custom_name = 'Sweet Lime (Sathukudi) 500g';
UPDATE shop_products SET display_order = 159 WHERE custom_name = 'Pear Green 500g';
UPDATE shop_products SET display_order = 160 WHERE custom_name = 'Avocado 1 Piece (Approx 200g)';
UPDATE shop_products SET display_order = 161 WHERE custom_name = 'Strawberry Punnet 200g';
UPDATE shop_products SET display_order = 162 WHERE custom_name = 'Raspberry Punnet 100g';
UPDATE shop_products SET display_order = 163 WHERE custom_name = 'Passion Fruit 2 Pcs';
UPDATE shop_products SET display_order = 164 WHERE custom_name = 'Fig Fresh 250g';
UPDATE shop_products SET display_order = 165 WHERE custom_name = 'Lychee 500g';
UPDATE shop_products SET display_order = 166 WHERE custom_name = 'Rambutan 500g';
UPDATE shop_products SET display_order = 167 WHERE custom_name = 'Star Fruit (Carambola) 250g';
UPDATE shop_products SET display_order = 168 WHERE custom_name = 'Dragon Fruit 1 Piece';
UPDATE shop_products SET display_order = 169 WHERE custom_name = 'Sweet Lime (Mosambi) 1kg';
UPDATE shop_products SET display_order = 170 WHERE custom_name = 'Pear Brown 500g';
UPDATE shop_products SET display_order = 171 WHERE custom_name = 'Gooseberry (Periya Nellikai) 250g';
UPDATE shop_products SET display_order = 172 WHERE custom_name = 'Coconut Water Fresh 1 Piece';
UPDATE shop_products SET display_order = 173 WHERE custom_name = 'Passion Fruit 500g';
UPDATE shop_products SET display_order = 174 WHERE custom_name = 'Guava 1kg';
UPDATE shop_products SET display_order = 175 WHERE custom_name = 'Toned Milk 500ml Pouch';
UPDATE shop_products SET display_order = 176 WHERE custom_name = 'Toned Milk 1L Pouch';
UPDATE shop_products SET display_order = 177 WHERE custom_name = 'Organic Toned Milk 500ml';
UPDATE shop_products SET display_order = 178 WHERE custom_name = 'Double Toned Milk 1L Pouch';
UPDATE shop_products SET display_order = 179 WHERE custom_name = 'Buttermilk (Morum) 200ml Pouch';
UPDATE shop_products SET display_order = 180 WHERE custom_name = 'Condensed Milk Tin 400g';
UPDATE shop_products SET display_order = 181 WHERE custom_name = 'Packaged Buttermilk Salted 1L';
UPDATE shop_products SET display_order = 182 WHERE custom_name = 'Mango Flavored Milk 200ml';
UPDATE shop_products SET display_order = 183 WHERE custom_name = 'Condensed Milk Tube 100g';
UPDATE shop_products SET display_order = 184 WHERE custom_name = 'Apple & Banana Milkshake 200ml';
UPDATE shop_products SET display_order = 185 WHERE custom_name = 'Full Cream Milk 500ml Pouch';
UPDATE shop_products SET display_order = 186 WHERE custom_name = 'Skimmed Milk Powder 200g';
UPDATE shop_products SET display_order = 187 WHERE custom_name = 'Full Cream Milk 1L Pouch';
UPDATE shop_products SET display_order = 188 WHERE custom_name = 'A2 Cow Milk 500ml';
UPDATE shop_products SET display_order = 189 WHERE custom_name = 'Low Fat Milk 1L Pouch';
UPDATE shop_products SET display_order = 190 WHERE custom_name = 'Full Cream Milk Powder 400g Tin';
UPDATE shop_products SET display_order = 191 WHERE custom_name = 'Buffalo Milk 500ml Pouch';
UPDATE shop_products SET display_order = 192 WHERE custom_name = 'Skimmed Milk 500ml Pouch';
UPDATE shop_products SET display_order = 193 WHERE custom_name = 'Soy Milk Plain 1L Tetra';
UPDATE shop_products SET display_order = 194 WHERE custom_name = 'Almond Milk Unsweetened 500ml';
UPDATE shop_products SET display_order = 195 WHERE custom_name = 'Goat Milk 500ml';
UPDATE shop_products SET display_order = 196 WHERE custom_name = 'Soy Milk Vanilla 1L Tetra';
UPDATE shop_products SET display_order = 197 WHERE custom_name = 'Set Curd (Thick Yogurt) 500g';
UPDATE shop_products SET display_order = 198 WHERE custom_name = 'Sour Curd 500g';
UPDATE shop_products SET display_order = 199 WHERE custom_name = 'Probiotic Curd 400g Cup';
UPDATE shop_products SET display_order = 200 WHERE custom_name = 'Sweetened Curd 400g Cup';
UPDATE shop_products SET display_order = 201 WHERE custom_name = 'Table Butter Salted 100g';
UPDATE shop_products SET display_order = 202 WHERE custom_name = 'Butter Salted 500g Block';
UPDATE shop_products SET display_order = 203 WHERE custom_name = 'White Butter Fresh 200g';
UPDATE shop_products SET display_order = 204 WHERE custom_name = 'Butter Unsalted 100g';
UPDATE shop_products SET display_order = 205 WHERE custom_name = 'Paneer Cubes 200g Pack';
UPDATE shop_products SET display_order = 206 WHERE custom_name = 'Fresh Paneer Block 200g';
UPDATE shop_products SET display_order = 207 WHERE custom_name = 'Cheese Slices Plain (10 Slices)';
UPDATE shop_products SET display_order = 208 WHERE custom_name = 'Whipping Cream Tetra Pack 200ml';
UPDATE shop_products SET display_order = 209 WHERE custom_name = 'Drinking Yogurt Mango 200ml';
UPDATE shop_products SET display_order = 210 WHERE custom_name = 'Processed Cheese Block 200g';
UPDATE shop_products SET display_order = 211 WHERE custom_name = 'Fresh Cream 200ml';
UPDATE shop_products SET display_order = 212 WHERE custom_name = 'Plain Lassi 200ml';
UPDATE shop_products SET display_order = 213 WHERE custom_name = 'Greek Yogurt Plain 100g Cup';
UPDATE shop_products SET display_order = 214 WHERE custom_name = 'Cheese Spread Plain 200g Jar';
UPDATE shop_products SET display_order = 215 WHERE custom_name = 'Flavored Lassi Strawberry 200ml';
UPDATE shop_products SET display_order = 216 WHERE custom_name = 'Fruit Yogurt Peach 100g Cup';
UPDATE shop_products SET display_order = 217 WHERE custom_name = 'Grated Cheese Mozzarella 200g';
UPDATE shop_products SET display_order = 218 WHERE custom_name = 'Ponni Boiled Rice 10kg';
UPDATE shop_products SET display_order = 219 WHERE custom_name = 'Ponni Boiled Rice 5kg';
UPDATE shop_products SET display_order = 220 WHERE custom_name = 'Sona Masoori Rice 10kg';
UPDATE shop_products SET display_order = 221 WHERE custom_name = 'Ponni Raw Rice 10kg';
UPDATE shop_products SET display_order = 222 WHERE custom_name = 'Sona Masoori Rice 5kg';
UPDATE shop_products SET display_order = 223 WHERE custom_name = 'Sona Masoori Raw Rice 5kg';
UPDATE shop_products SET display_order = 224 WHERE custom_name = 'Ponni Boiled Rice 25kg';
UPDATE shop_products SET display_order = 225 WHERE custom_name = 'Rice Flour 500g';
UPDATE shop_products SET display_order = 226 WHERE custom_name = 'Puttu Podi (Rice/Wheat) 500g';
UPDATE shop_products SET display_order = 227 WHERE custom_name = 'Rice Flour Wet Ground 500g';
UPDATE shop_products SET display_order = 228 WHERE custom_name = 'Idli Rice 5kg';
UPDATE shop_products SET display_order = 229 WHERE custom_name = 'Raw Rice (Pacharisi) 1kg';
UPDATE shop_products SET display_order = 230 WHERE custom_name = 'Brown Rice 1kg';
UPDATE shop_products SET display_order = 231 WHERE custom_name = 'Basmati Rice Standard 1kg';
UPDATE shop_products SET display_order = 232 WHERE custom_name = 'Matta Rice 5kg';
UPDATE shop_products SET display_order = 233 WHERE custom_name = 'Basmati Rice Premium 1kg';
UPDATE shop_products SET display_order = 234 WHERE custom_name = 'Idli Rice 10kg';
UPDATE shop_products SET display_order = 235 WHERE custom_name = 'Rice Boiled Premium 5kg';
UPDATE shop_products SET display_order = 236 WHERE custom_name = 'Black Basmati Rice 1kg';
UPDATE shop_products SET display_order = 237 WHERE custom_name = 'Thooyamalli Rice 1kg';
UPDATE shop_products SET display_order = 238 WHERE custom_name = 'Seeraga Samba Rice 500g';
UPDATE shop_products SET display_order = 239 WHERE custom_name = 'Red Rice Boiled 1kg';
UPDATE shop_products SET display_order = 240 WHERE custom_name = 'Raw Rice (Pacharisi) 5kg';
UPDATE shop_products SET display_order = 241 WHERE custom_name = 'Basmati Rice Standard 5kg';
UPDATE shop_products SET display_order = 242 WHERE custom_name = 'Brown Rice 5kg';
UPDATE shop_products SET display_order = 243 WHERE custom_name = 'Toor Dal Standard 1kg';
UPDATE shop_products SET display_order = 244 WHERE custom_name = 'Toor Dal Polished 500g';
UPDATE shop_products SET display_order = 245 WHERE custom_name = 'Toor Dal Premium 1kg';
UPDATE shop_products SET display_order = 246 WHERE custom_name = 'Toor Dal Standard 5kg';
UPDATE shop_products SET display_order = 247 WHERE custom_name = 'Toor Dal Premium 5kg';
UPDATE shop_products SET display_order = 248 WHERE custom_name = 'Urad Dal Whole 1kg';
UPDATE shop_products SET display_order = 249 WHERE custom_name = 'Urad Dal Split (Gota) 500g';
UPDATE shop_products SET display_order = 250 WHERE custom_name = 'Black Urad Dal Whole with Skin 1kg';
UPDATE shop_products SET display_order = 251 WHERE custom_name = 'Black Urad Dal Split (Polippu) 500g';
UPDATE shop_products SET display_order = 252 WHERE custom_name = 'Urad Dal Split 1kg';
UPDATE shop_products SET display_order = 253 WHERE custom_name = 'Urad Dal Whole 5kg';
UPDATE shop_products SET display_order = 254 WHERE custom_name = 'Moong Dal Split 1kg';
UPDATE shop_products SET display_order = 255 WHERE custom_name = 'Split Moong Dal with Skin 500g';
UPDATE shop_products SET display_order = 256 WHERE custom_name = 'Moong Dal Split 5kg';
UPDATE shop_products SET display_order = 257 WHERE custom_name = 'Chana Dal 500g';
UPDATE shop_products SET display_order = 258 WHERE custom_name = 'Roasted Chana Dal 200g';
UPDATE shop_products SET display_order = 259 WHERE custom_name = 'Chana Dal 1kg';
UPDATE shop_products SET display_order = 260 WHERE custom_name = 'Wheat Atta (Whole Wheat Flour) 5kg';
UPDATE shop_products SET display_order = 261 WHERE custom_name = 'Wheat Atta Multi-Grain 1kg';
UPDATE shop_products SET display_order = 262 WHERE custom_name = 'Wheat Atta (Whole Wheat Flour) 10kg';
UPDATE shop_products SET display_order = 263 WHERE custom_name = 'Ragi Flour (Finger Millet) 1kg';
UPDATE shop_products SET display_order = 264 WHERE custom_name = 'Maida (All-Purpose Flour) 500g';
UPDATE shop_products SET display_order = 265 WHERE custom_name = 'Whole Wheat Flour 1kg Pouch';
UPDATE shop_products SET display_order = 266 WHERE custom_name = 'Besan (Gram Flour) 500g';
UPDATE shop_products SET display_order = 267 WHERE custom_name = 'Bajra Flour (Pearl Millet) 500g';
UPDATE shop_products SET display_order = 268 WHERE custom_name = 'Corn Flour 100g';
UPDATE shop_products SET display_order = 269 WHERE custom_name = 'Wheat Flour Wholemeal 1kg';
UPDATE shop_products SET display_order = 270 WHERE custom_name = 'Maida (All-Purpose Flour) 1kg';
UPDATE shop_products SET display_order = 271 WHERE custom_name = 'Corn Flour 500g';
UPDATE shop_products SET display_order = 272 WHERE custom_name = 'Ragi Flour 5kg';
UPDATE shop_products SET display_order = 273 WHERE custom_name = 'Besan (Gram Flour) 1kg';
UPDATE shop_products SET display_order = 274 WHERE custom_name = 'Bengal Gram (Pottukadalai) 200g';
UPDATE shop_products SET display_order = 275 WHERE custom_name = 'White Peas (Pattani) 500g';
UPDATE shop_products SET display_order = 276 WHERE custom_name = 'Rajma (Kidney Beans) 500g';
UPDATE shop_products SET display_order = 277 WHERE custom_name = 'Black Chickpeas (Kondaikadalai) 500g';
UPDATE shop_products SET display_order = 278 WHERE custom_name = 'White Chickpeas (Kabuli Chana) 500g';
UPDATE shop_products SET display_order = 279 WHERE custom_name = 'Masoor Dal Red 500g';
UPDATE shop_products SET display_order = 280 WHERE custom_name = 'Brown Chana Whole 500g';
UPDATE shop_products SET display_order = 281 WHERE custom_name = 'Kidney Beans White 500g';
UPDATE shop_products SET display_order = 282 WHERE custom_name = 'Black Gram Whole (Karamani) 500g';
UPDATE shop_products SET display_order = 283 WHERE custom_name = 'Horse Gram (Kollu) 500g';
UPDATE shop_products SET display_order = 284 WHERE custom_name = 'Roasted Gram Dal (Split) 500g';
UPDATE shop_products SET display_order = 285 WHERE custom_name = 'Green Peas Dried 500g';
UPDATE shop_products SET display_order = 286 WHERE custom_name = 'Green Gram Whole (Pachai Payaru) 1kg';
UPDATE shop_products SET display_order = 287 WHERE custom_name = 'Split Masoor Dal 1kg';
UPDATE shop_products SET display_order = 288 WHERE custom_name = 'Rajma Chitra (Spotted) 500g';
UPDATE shop_products SET display_order = 289 WHERE custom_name = 'Green Gram Split (Pasi Paruppu) 1kg';
UPDATE shop_products SET display_order = 290 WHERE custom_name = 'Roasted Semolina (Rava/Sooji) 500g';
UPDATE shop_products SET display_order = 291 WHERE custom_name = 'Plain Wheat Semolina (Rava/Sooji) 500g';
UPDATE shop_products SET display_order = 292 WHERE custom_name = 'Potato Starch 100g';
UPDATE shop_products SET display_order = 293 WHERE custom_name = 'Pearl Millet (Kambu) 1kg';
UPDATE shop_products SET display_order = 294 WHERE custom_name = 'Finger Millet (Ragi) Whole 1kg';
UPDATE shop_products SET display_order = 295 WHERE custom_name = 'Sago (Sabudana) 250g';
UPDATE shop_products SET display_order = 296 WHERE custom_name = 'Wheat Dalia (Broken Wheat) 500g';
UPDATE shop_products SET display_order = 297 WHERE custom_name = 'Jowar (Sorghum) Whole 1kg';
UPDATE shop_products SET display_order = 298 WHERE custom_name = 'Foxtail Millet (Thinai) 1kg';
UPDATE shop_products SET display_order = 299 WHERE custom_name = 'Barley 500g';
UPDATE shop_products SET display_order = 300 WHERE custom_name = 'Groundnut Oil 1L Pouch';
UPDATE shop_products SET display_order = 301 WHERE custom_name = 'Refined Sunflower Oil 2L Jar';
UPDATE shop_products SET display_order = 302 WHERE custom_name = 'Gingelly (Sesame) Oil 500ml';
UPDATE shop_products SET display_order = 303 WHERE custom_name = 'Coconut Oil 500ml Jar';
UPDATE shop_products SET display_order = 304 WHERE custom_name = 'Premium Ghee 500ml Tin';
UPDATE shop_products SET display_order = 305 WHERE custom_name = 'Refined Palmolein Oil 1L Pouch';
UPDATE shop_products SET display_order = 306 WHERE custom_name = 'Rice Bran Oil 1L Pouch';
UPDATE shop_products SET display_order = 307 WHERE custom_name = 'Groundnut Oil Cold Pressed 1L';
UPDATE shop_products SET display_order = 308 WHERE custom_name = 'Sesame Oil Cold Pressed 500ml';
UPDATE shop_products SET display_order = 309 WHERE custom_name = 'Olive Oil Extra Virgin 250ml';
UPDATE shop_products SET display_order = 310 WHERE custom_name = 'Avocado Oil 100ml';
UPDATE shop_products SET display_order = 311 WHERE custom_name = 'Refined Oil Sunflower 1L Bottle';
UPDATE shop_products SET display_order = 312 WHERE custom_name = 'Mustard Oil Pure 500ml';
UPDATE shop_products SET display_order = 313 WHERE custom_name = 'Groundnut Oil (Standard) 2L Jar';
UPDATE shop_products SET display_order = 314 WHERE custom_name = 'Refined Sunflower Oil 5L Can';
UPDATE shop_products SET display_order = 315 WHERE custom_name = 'Groundnut Oil Cold Pressed 5L Can';
UPDATE shop_products SET display_order = 316 WHERE custom_name = 'Ghee Premium 1L Jar';
UPDATE shop_products SET display_order = 317 WHERE custom_name = 'Coconut Oil Cold Pressed 500ml';
UPDATE shop_products SET display_order = 318 WHERE custom_name = 'Olive Oil Pomace 500ml';
UPDATE shop_products SET display_order = 319 WHERE custom_name = 'Refined Palmolein Oil 5L Can';
UPDATE shop_products SET display_order = 320 WHERE custom_name = 'Gingelly (Sesame) Oil 1L Jar';
UPDATE shop_products SET display_order = 321 WHERE custom_name = 'Coconut Oil 1L Jar';
UPDATE shop_products SET display_order = 322 WHERE custom_name = 'Turmeric Powder 100g';
UPDATE shop_products SET display_order = 323 WHERE custom_name = 'Turmeric Powder 500g';
UPDATE shop_products SET display_order = 324 WHERE custom_name = 'Turmeric Stick Whole 100g';
UPDATE shop_products SET display_order = 325 WHERE custom_name = 'Chilli Powder (Medium Hot) 200g';
UPDATE shop_products SET display_order = 326 WHERE custom_name = 'Chilli Powder (Kashmiri) 100g';
UPDATE shop_products SET display_order = 327 WHERE custom_name = 'Chilli Powder (Medium Hot) 500g';
UPDATE shop_products SET display_order = 328 WHERE custom_name = 'Coriander Powder 200g';
UPDATE shop_products SET display_order = 329 WHERE custom_name = 'Coriander Powder 500g';
UPDATE shop_products SET display_order = 330 WHERE custom_name = 'Jeera (Cumin Seeds) 100g';
UPDATE shop_products SET display_order = 331 WHERE custom_name = 'Cumin Seeds (Jeera) 500g';
UPDATE shop_products SET display_order = 332 WHERE custom_name = 'Mustard Seeds 100g';
UPDATE shop_products SET display_order = 333 WHERE custom_name = 'Black Pepper Powder 50g';
UPDATE shop_products SET display_order = 334 WHERE custom_name = 'White Pepper Powder 50g';
UPDATE shop_products SET display_order = 335 WHERE custom_name = 'Pepper Black Powder 100g';
UPDATE shop_products SET display_order = 336 WHERE custom_name = 'Pepper Corns Black 50g';
UPDATE shop_products SET display_order = 337 WHERE custom_name = 'Black Pepper Corns 250g';
UPDATE shop_products SET display_order = 338 WHERE custom_name = 'Rock Salt (Kallu Uppu) 1kg';
UPDATE shop_products SET display_order = 339 WHERE custom_name = 'Iodized Salt Powder 1kg';
UPDATE shop_products SET display_order = 340 WHERE custom_name = 'Himalayan Pink Salt 500g';
UPDATE shop_products SET display_order = 341 WHERE custom_name = 'Rock Salt (Kallu Uppu) 5kg';
UPDATE shop_products SET display_order = 342 WHERE custom_name = 'Iodized Salt Powder 500g';
UPDATE shop_products SET display_order = 343 WHERE custom_name = 'Rock Salt (Kallu Uppu) 10kg';
UPDATE shop_products SET display_order = 344 WHERE custom_name = 'Tamarind Seedless 200g';
UPDATE shop_products SET display_order = 345 WHERE custom_name = 'Tamarind Concentrate 200g';
UPDATE shop_products SET display_order = 346 WHERE custom_name = 'Tomato Paste Canned 200g';
UPDATE shop_products SET display_order = 347 WHERE custom_name = 'Tamarind Seeded 500g';
UPDATE shop_products SET display_order = 348 WHERE custom_name = 'Sambar Powder Standard 100g';
UPDATE shop_products SET display_order = 349 WHERE custom_name = 'Garam Masala Powder 50g';
UPDATE shop_products SET display_order = 350 WHERE custom_name = 'Chicken Masala Powder 50g';
UPDATE shop_products SET display_order = 351 WHERE custom_name = 'Fish Fry Masala Powder 50g';
UPDATE shop_products SET display_order = 352 WHERE custom_name = 'Bisibelebath Powder 100g';
UPDATE shop_products SET display_order = 353 WHERE custom_name = 'Garlic Powder 50g';
UPDATE shop_products SET display_order = 354 WHERE custom_name = 'Asafoetida Powder (Hing) 50g';
UPDATE shop_products SET display_order = 355 WHERE custom_name = 'Mango Powder (Amchur) 50g';
UPDATE shop_products SET display_order = 356 WHERE custom_name = 'Cinnamon Powder 50g';
UPDATE shop_products SET display_order = 357 WHERE custom_name = 'Star Anise Powder 50g';
UPDATE shop_products SET display_order = 358 WHERE custom_name = 'Cardamom Powder 25g';
UPDATE shop_products SET display_order = 359 WHERE custom_name = 'Biryani Masala Powder 100g';
UPDATE shop_products SET display_order = 360 WHERE custom_name = 'Curry Mix Powder Home Made 100g';
UPDATE shop_products SET display_order = 361 WHERE custom_name = 'Onion Powder 50g';
UPDATE shop_products SET display_order = 362 WHERE custom_name = 'Rasam Powder Home Made 100g';
UPDATE shop_products SET display_order = 363 WHERE custom_name = 'Ginger Powder 100g';
UPDATE shop_products SET display_order = 364 WHERE custom_name = 'Onion Powder 100g';
UPDATE shop_products SET display_order = 365 WHERE custom_name = 'All Spice Powder 50g';
UPDATE shop_products SET display_order = 366 WHERE custom_name = 'Sambar Powder Standard 500g';
UPDATE shop_products SET display_order = 367 WHERE custom_name = 'Dried Ginger (Sukku) Powder 50g';
UPDATE shop_products SET display_order = 368 WHERE custom_name = 'Cardamom Green 25g';
UPDATE shop_products SET display_order = 369 WHERE custom_name = 'Cinnamon Stick 50g';
UPDATE shop_products SET display_order = 370 WHERE custom_name = 'Fenugreek Seeds 100g';
UPDATE shop_products SET display_order = 371 WHERE custom_name = 'Bay Leaf 50g';
UPDATE shop_products SET display_order = 372 WHERE custom_name = 'Cloves (Lavangam) 50g';
UPDATE shop_products SET display_order = 373 WHERE custom_name = 'Star Anise 25g';
UPDATE shop_products SET display_order = 374 WHERE custom_name = 'Red Chili Whole 100g';
UPDATE shop_products SET display_order = 375 WHERE custom_name = 'Poppy Seeds (Kasa Kasa) 50g';
UPDATE shop_products SET display_order = 376 WHERE custom_name = 'Fennel Seeds (Sombu) 100g';
UPDATE shop_products SET display_order = 377 WHERE custom_name = 'Poppy Seeds White 50g';
UPDATE shop_products SET display_order = 378 WHERE custom_name = 'Nutmeg Whole (Jathikai) 25g';
UPDATE shop_products SET display_order = 379 WHERE custom_name = 'Dried Ginger (Sukku) 100g';
UPDATE shop_products SET display_order = 380 WHERE custom_name = 'Dried Methi Leaves (Kasoori Methi) 50g';
UPDATE shop_products SET display_order = 381 WHERE custom_name = 'Panch Pooran Mix 100g';
UPDATE shop_products SET display_order = 382 WHERE custom_name = 'Saffron (Kesar) 1g';
UPDATE shop_products SET display_order = 383 WHERE custom_name = 'Poppy Seeds Black 50g';
UPDATE shop_products SET display_order = 384 WHERE custom_name = 'Garlic Whole 500g';
UPDATE shop_products SET display_order = 385 WHERE custom_name = 'Cinnamon Stick 100g';
UPDATE shop_products SET display_order = 386 WHERE custom_name = 'Black Cardamom 50g';
UPDATE shop_products SET display_order = 387 WHERE custom_name = 'Plain Bread Large';
UPDATE shop_products SET display_order = 388 WHERE custom_name = 'Wheat Bread Medium';
UPDATE shop_products SET display_order = 389 WHERE custom_name = 'Coconut Rusk 200g';
UPDATE shop_products SET display_order = 390 WHERE custom_name = 'Whole Wheat Bread Small';
UPDATE shop_products SET display_order = 391 WHERE custom_name = 'Garlic Bread Mix 200g';
UPDATE shop_products SET display_order = 392 WHERE custom_name = 'Butter Toast 200g';
UPDATE shop_products SET display_order = 393 WHERE custom_name = 'Vermicelli Roasted 200g';
UPDATE shop_products SET display_order = 394 WHERE custom_name = 'Flattened Rice (Poha) Thick 500g';
UPDATE shop_products SET display_order = 395 WHERE custom_name = 'Rice Flakes (Poha) Thin 500g';
UPDATE shop_products SET display_order = 396 WHERE custom_name = 'Poha (Rice Flakes) Thin 1kg';
UPDATE shop_products SET display_order = 397 WHERE custom_name = 'Rice Vermicelli (Sevai) 200g';
UPDATE shop_products SET display_order = 398 WHERE custom_name = 'Brown Rice Poha 500g';
UPDATE shop_products SET display_order = 399 WHERE custom_name = 'Filter Coffee Powder Standard 250g';
UPDATE shop_products SET display_order = 400 WHERE custom_name = 'Black Tea Dust 500g';
UPDATE shop_products SET display_order = 401 WHERE custom_name = 'Instant Coffee Powder 50g Jar';
UPDATE shop_products SET display_order = 402 WHERE custom_name = 'Green Tea Bags (25 Pcs)';
UPDATE shop_products SET display_order = 403 WHERE custom_name = 'Instant Tea Premix Masala';
UPDATE shop_products SET display_order = 404 WHERE custom_name = 'Black Coffee Instant Powder 50g';
UPDATE shop_products SET display_order = 405 WHERE custom_name = 'Herbal Tea Bags (25 Pcs)';
UPDATE shop_products SET display_order = 406 WHERE custom_name = 'Green Tea with Lemon Flavor (10 Bags)';
UPDATE shop_products SET display_order = 407 WHERE custom_name = 'Espresso Coffee Powder 100g';
UPDATE shop_products SET display_order = 408 WHERE custom_name = 'Instant Coffee Chicory Mix 100g';
UPDATE shop_products SET display_order = 409 WHERE custom_name = 'Tea Leaves Premium Black 250g';
UPDATE shop_products SET display_order = 410 WHERE custom_name = 'Green Tea Pure Darjeeling (25 Bags)';
UPDATE shop_products SET display_order = 411 WHERE custom_name = 'Filter Coffee Powder Dark Roast 500g';
UPDATE shop_products SET display_order = 412 WHERE custom_name = 'Tea Dust Premium 1kg';
UPDATE shop_products SET display_order = 413 WHERE custom_name = 'Decaffeinated Coffee Powder 50g';
UPDATE shop_products SET display_order = 414 WHERE custom_name = 'Green Tea Mint Flavor (10 Bags)';
UPDATE shop_products SET display_order = 415 WHERE custom_name = 'Green Tea Jasmine Flavor (25 Bags)';
UPDATE shop_products SET display_order = 416 WHERE custom_name = 'Cappuccino Instant Mix (5 Sachets)';
UPDATE shop_products SET display_order = 417 WHERE custom_name = 'Instant Tea Premix Plain';
UPDATE shop_products SET display_order = 418 WHERE custom_name = 'Jaggery Cubes 1kg';
UPDATE shop_products SET display_order = 419 WHERE custom_name = 'White Crystal Sugar 1kg';
UPDATE shop_products SET display_order = 420 WHERE custom_name = 'Rock Sugar (Kalkandu) 250g';
UPDATE shop_products SET display_order = 421 WHERE custom_name = 'Honey Natural 200g Jar';
UPDATE shop_products SET display_order = 422 WHERE custom_name = 'Dates Syrup 300g';
UPDATE shop_products SET display_order = 423 WHERE custom_name = 'Refined Sugar Powder 500g';
UPDATE shop_products SET display_order = 424 WHERE custom_name = 'Organic Jaggery Powder 500g';
UPDATE shop_products SET display_order = 425 WHERE custom_name = 'Brown Sugar 500g';
UPDATE shop_products SET display_order = 426 WHERE custom_name = 'Artificial Sweetener Tablets (100 Pcs)';
UPDATE shop_products SET display_order = 427 WHERE custom_name = 'Corn Syrup 200g';
UPDATE shop_products SET display_order = 428 WHERE custom_name = 'Jaggery Powder 500g';
UPDATE shop_products SET display_order = 429 WHERE custom_name = 'White Crystal Sugar 5kg';
UPDATE shop_products SET display_order = 430 WHERE custom_name = 'Sugar Cubes White 250g';
UPDATE shop_products SET display_order = 431 WHERE custom_name = 'Jaggery Cubes 5kg';
UPDATE shop_products SET display_order = 432 WHERE custom_name = 'Samosa Ready to Fry (Pkt of 10)';
UPDATE shop_products SET display_order = 433 WHERE custom_name = 'Vegetable Cutlet Frozen (Pkt of 5)';
UPDATE shop_products SET display_order = 434 WHERE custom_name = 'Paneer Bhurji Frozen 200g';
UPDATE shop_products SET display_order = 435 WHERE custom_name = 'Pasta Macaroni 500g';
UPDATE shop_products SET display_order = 436 WHERE custom_name = 'Noodles Instant Chicken Flavor (Pkt of 4)';
UPDATE shop_products SET display_order = 437 WHERE custom_name = 'Whole Wheat Pasta Penne 250g';
UPDATE shop_products SET display_order = 438 WHERE custom_name = 'Noodles Instant Veggie Flavor (Pkt of 4)';
UPDATE shop_products SET display_order = 439 WHERE custom_name = 'Ginger Garlic Paste 200g';
UPDATE shop_products SET display_order = 440 WHERE custom_name = 'Instant Idli Mix 200g';
UPDATE shop_products SET display_order = 441 WHERE custom_name = 'Instant Dosa Mix 200g';
UPDATE shop_products SET display_order = 442 WHERE custom_name = 'Tomato Soup Powder Instant 50g';
UPDATE shop_products SET display_order = 443 WHERE custom_name = 'Instant Gulab Jamun Mix 200g';
UPDATE shop_products SET display_order = 444 WHERE custom_name = 'Coconut Milk Powder 100g';
UPDATE shop_products SET display_order = 445 WHERE custom_name = 'Instant Rasam Mix 100g';
UPDATE shop_products SET display_order = 446 WHERE custom_name = 'Rice Flour Idiyappam Mix 500g';
UPDATE shop_products SET display_order = 447 WHERE custom_name = 'Soya Chunks Small 200g';
UPDATE shop_products SET display_order = 448 WHERE custom_name = 'Vada Mix Instant 200g';
UPDATE shop_products SET display_order = 449 WHERE custom_name = 'Vegetable Biryani Mix 200g';
UPDATE shop_products SET display_order = 450 WHERE custom_name = 'Ready-to-Eat Rice Pulav 250g Pouch';
UPDATE shop_products SET display_order = 451 WHERE custom_name = 'Glucose Biscuits 100g';
UPDATE shop_products SET display_order = 452 WHERE custom_name = 'Salted Crackers Biscuits 200g';
UPDATE shop_products SET display_order = 453 WHERE custom_name = 'Cream Biscuits Strawberry 150g';
UPDATE shop_products SET display_order = 454 WHERE custom_name = 'Chocolate Chip Cookies 100g';
UPDATE shop_products SET display_order = 455 WHERE custom_name = 'Butter Cookies 150g';
UPDATE shop_products SET display_order = 456 WHERE custom_name = 'Tea Biscuits (Rusks) 200g';
UPDATE shop_products SET display_order = 457 WHERE custom_name = 'Coconut Biscuits 150g';
UPDATE shop_products SET display_order = 458 WHERE custom_name = 'Milk Biscuits 100g';
UPDATE shop_products SET display_order = 459 WHERE custom_name = 'Digestive Biscuits 150g';
UPDATE shop_products SET display_order = 460 WHERE custom_name = 'Wafer Biscuits Chocolate 75g';
UPDATE shop_products SET display_order = 461 WHERE custom_name = 'Marie Gold Biscuits 100g';
UPDATE shop_products SET display_order = 462 WHERE custom_name = 'Cream Biscuits Chocolate 150g';
UPDATE shop_products SET display_order = 463 WHERE custom_name = 'Bourbon Biscuits Chocolate 150g';
UPDATE shop_products SET display_order = 464 WHERE custom_name = 'Shortbread Cookies 100g';
UPDATE shop_products SET display_order = 465 WHERE custom_name = 'Cream Biscuits Orange 150g';
UPDATE shop_products SET display_order = 466 WHERE custom_name = 'Cream Biscuits Vanilla 150g';
UPDATE shop_products SET display_order = 467 WHERE custom_name = 'Parle G Biscuits 200g';
UPDATE shop_products SET display_order = 468 WHERE custom_name = 'Potato Chips Salted 50g';
UPDATE shop_products SET display_order = 469 WHERE custom_name = 'Potato Chips Tomato Flavor 100g';
UPDATE shop_products SET display_order = 470 WHERE custom_name = 'Banana Chips Salted 100g';
UPDATE shop_products SET display_order = 471 WHERE custom_name = 'Pepper Chips Thin 75g';
UPDATE shop_products SET display_order = 472 WHERE custom_name = 'Puff Corn Cheese Flavor 50g';
UPDATE shop_products SET display_order = 473 WHERE custom_name = 'Potato Wafers Masala 50g';
UPDATE shop_products SET display_order = 474 WHERE custom_name = 'Banana Chips Spicy 100g';
UPDATE shop_products SET display_order = 475 WHERE custom_name = 'Dry Fruit Bar 50g';
UPDATE shop_products SET display_order = 476 WHERE custom_name = 'Energy Bar Almond & Dates';
UPDATE shop_products SET display_order = 477 WHERE custom_name = 'Mixture (Savory Indian Snack) 200g';
UPDATE shop_products SET display_order = 478 WHERE custom_name = 'Madras Murukku 150g';
UPDATE shop_products SET display_order = 479 WHERE custom_name = 'Plain Sev (Thin Vermicelli Snack) 100g';
UPDATE shop_products SET display_order = 480 WHERE custom_name = 'Pepper Thattai 100g';
UPDATE shop_products SET display_order = 481 WHERE custom_name = 'Bhujia Sev Spicy 150g';
UPDATE shop_products SET display_order = 482 WHERE custom_name = 'Roasted Peanuts Salted 100g';
UPDATE shop_products SET display_order = 483 WHERE custom_name = 'Chakli (Murukku) Plain 150g';
UPDATE shop_products SET display_order = 484 WHERE custom_name = 'Salted Mixture Andhra Style 150g';
UPDATE shop_products SET display_order = 485 WHERE custom_name = 'Spicy Aloo Bhujia 100g';
UPDATE shop_products SET display_order = 486 WHERE custom_name = 'Cashew Pakoda 150g';
UPDATE shop_products SET display_order = 487 WHERE custom_name = 'Mixture Spicy Madras 150g';
UPDATE shop_products SET display_order = 488 WHERE custom_name = 'Namkeen Sev Spicy 200g';
UPDATE shop_products SET display_order = 489 WHERE custom_name = 'Mixture Diet (Low Oil) 150g';
UPDATE shop_products SET display_order = 490 WHERE custom_name = 'Ribbon Pakoda 150g';
UPDATE shop_products SET display_order = 491 WHERE custom_name = 'Mixture Kerala Style 200g';
UPDATE shop_products SET display_order = 492 WHERE custom_name = 'Murukku Butter Flavor 150g';
UPDATE shop_products SET display_order = 493 WHERE custom_name = 'Chakli Garlic Flavor 150g';
UPDATE shop_products SET display_order = 494 WHERE custom_name = 'Mixture Bombay Style 200g';
UPDATE shop_products SET display_order = 495 WHERE custom_name = 'Appalam (Papad) Rice 200g';
UPDATE shop_products SET display_order = 496 WHERE custom_name = 'Health Drink Chocolate 200g Refill';
UPDATE shop_products SET display_order = 497 WHERE custom_name = 'Badam Drink Mix 100g';
UPDATE shop_products SET display_order = 498 WHERE custom_name = 'Energy Drink Lime Flavor 500ml';
UPDATE shop_products SET display_order = 499 WHERE custom_name = 'Malted Health Drink Standard 500g';
UPDATE shop_products SET display_order = 500 WHERE custom_name = 'Hot Chocolate Mix 200g';
UPDATE shop_products SET display_order = 501 WHERE custom_name = 'Boost Health Drink 200g Jar';
UPDATE shop_products SET display_order = 502 WHERE custom_name = 'Protein Health Mix Powder 500g';
UPDATE shop_products SET display_order = 503 WHERE custom_name = 'Health Drink Protein Supplement 500g';
UPDATE shop_products SET display_order = 504 WHERE custom_name = 'Bournvita Health Drink 500g Jar';
UPDATE shop_products SET display_order = 505 WHERE custom_name = 'Lemon Soda Sweetened 600ml Bottle';
UPDATE shop_products SET display_order = 506 WHERE custom_name = 'Jeera Soda 600ml Bottle';
UPDATE shop_products SET display_order = 507 WHERE custom_name = 'Orange Soda 600ml Bottle';
UPDATE shop_products SET display_order = 508 WHERE custom_name = 'Ginger Ale 300ml Can';
UPDATE shop_products SET display_order = 509 WHERE custom_name = 'Plain Soda Water 1L Bottle';
UPDATE shop_products SET display_order = 510 WHERE custom_name = 'Diet Cola Can 300ml';
UPDATE shop_products SET display_order = 511 WHERE custom_name = 'Lemonade Fresh 500ml';
UPDATE shop_products SET display_order = 512 WHERE custom_name = 'Energy Drink Original 300ml Can';
UPDATE shop_products SET display_order = 513 WHERE custom_name = 'Energy Drink Zero Sugar 300ml';
UPDATE shop_products SET display_order = 514 WHERE custom_name = 'Grape Soda 600ml Bottle';
UPDATE shop_products SET display_order = 515 WHERE custom_name = 'Packaged Drinking Water 1L Bottle';
UPDATE shop_products SET display_order = 516 WHERE custom_name = 'Apple Juice Tetra Pack 1L';
UPDATE shop_products SET display_order = 517 WHERE custom_name = 'Mango Nectar Drink 500ml';
UPDATE shop_products SET display_order = 518 WHERE custom_name = 'Tender Coconut Water Tetra 200ml';
UPDATE shop_products SET display_order = 519 WHERE custom_name = 'Sparkling Water Bottle 1L';
UPDATE shop_products SET display_order = 520 WHERE custom_name = 'Mineral Water 2L Bottle';
UPDATE shop_products SET display_order = 521 WHERE custom_name = 'Guava Nectar Drink 1L';
UPDATE shop_products SET display_order = 522 WHERE custom_name = 'Coconut Water Canned 300ml';
UPDATE shop_products SET display_order = 523 WHERE custom_name = 'Sugar Cane Juice Canned 300ml';
UPDATE shop_products SET display_order = 524 WHERE custom_name = 'Grape Juice Red 1L Bottle';
UPDATE shop_products SET display_order = 525 WHERE custom_name = 'Tomato Juice Canned 300ml';
UPDATE shop_products SET display_order = 526 WHERE custom_name = 'Tender Coconut Pulp Canned 200g';
UPDATE shop_products SET display_order = 527 WHERE custom_name = 'Cranberry Juice 1L Bottle';
UPDATE shop_products SET display_order = 528 WHERE custom_name = 'Mango Shake 1L Tetra';
UPDATE shop_products SET display_order = 529 WHERE custom_name = 'Bottled Spring Water 1L';
UPDATE shop_products SET display_order = 530 WHERE custom_name = 'Groundnut Raw 500g';
UPDATE shop_products SET display_order = 531 WHERE custom_name = 'Flax Seeds 100g';
UPDATE shop_products SET display_order = 532 WHERE custom_name = 'Sesame Seeds White 100g';
UPDATE shop_products SET display_order = 533 WHERE custom_name = 'Pumpkin Seeds 50g';
UPDATE shop_products SET display_order = 534 WHERE custom_name = 'Peanuts Boiled/Roasted 500g';
UPDATE shop_products SET display_order = 535 WHERE custom_name = 'Chia Seeds 100g';
UPDATE shop_products SET display_order = 536 WHERE custom_name = 'Sunflower Seeds 100g';
UPDATE shop_products SET display_order = 537 WHERE custom_name = 'Sesame Seeds Black 100g';
UPDATE shop_products SET display_order = 538 WHERE custom_name = 'Mango Pickle Oil Based 300g Jar';
UPDATE shop_products SET display_order = 539 WHERE custom_name = 'Tomato Ketchup 500g Bottle';
UPDATE shop_products SET display_order = 540 WHERE custom_name = 'Soy Sauce Standard 200ml';
UPDATE shop_products SET display_order = 541 WHERE custom_name = 'White Vinegar Standard 200ml';
UPDATE shop_products SET display_order = 542 WHERE custom_name = 'Pickle Mixed Vegetable 300g Jar';
UPDATE shop_products SET display_order = 543 WHERE custom_name = 'Chilli Sauce Red 200ml';
UPDATE shop_products SET display_order = 544 WHERE custom_name = 'Mayonnaise Eggless 200g';
UPDATE shop_products SET display_order = 545 WHERE custom_name = 'Vinegar Balsamic 100ml';
UPDATE shop_products SET display_order = 546 WHERE custom_name = 'Garlic Pickle Oil Based 300g Jar';
UPDATE shop_products SET display_order = 547 WHERE custom_name = 'Green Chilli Pickle 200g Jar';
UPDATE shop_products SET display_order = 548 WHERE custom_name = 'Pizza Pasta Sauce 250g';
UPDATE shop_products SET display_order = 549 WHERE custom_name = 'Vinegar Apple Cider 200ml';
UPDATE shop_products SET display_order = 550 WHERE custom_name = 'Oregano Seasoning 30g Jar';
UPDATE shop_products SET display_order = 551 WHERE custom_name = 'Jalapeno Slices Canned 200g';
UPDATE shop_products SET display_order = 552 WHERE custom_name = 'Pickled Ginger 100g Jar';
UPDATE shop_products SET display_order = 553 WHERE custom_name = 'Pickle Lemon 300g Jar';
UPDATE shop_products SET display_order = 554 WHERE custom_name = 'Green Chilli Sauce 200ml';
UPDATE shop_products SET display_order = 555 WHERE custom_name = 'Vinegar White 1L Bottle';
UPDATE shop_products SET display_order = 556 WHERE custom_name = 'Pickle Mixed Vegetable 1kg Jar';
UPDATE shop_products SET display_order = 557 WHERE custom_name = 'Tomato Ketchup 1kg Bottle';
UPDATE shop_products SET display_order = 558 WHERE custom_name = 'Neem & Tulasi Bathing Soap (Pack of 4)';
UPDATE shop_products SET display_order = 559 WHERE custom_name = 'Sandalwood Beauty Soap (125g)';
UPDATE shop_products SET display_order = 560 WHERE custom_name = 'Glycerin Transparent Soap (75g)';
UPDATE shop_products SET display_order = 561 WHERE custom_name = 'Body Wash Rose Fragrance 250ml';
UPDATE shop_products SET display_order = 562 WHERE custom_name = 'Talcum Powder Sandalwood 150g';
UPDATE shop_products SET display_order = 563 WHERE custom_name = 'Deodorant Spray Men Sport 150ml';
UPDATE shop_products SET display_order = 564 WHERE custom_name = 'Deodorant Roll-On Women Floral 50ml';
UPDATE shop_products SET display_order = 565 WHERE custom_name = 'Medicated Soap Anti-Bacterial 75g';
UPDATE shop_products SET display_order = 566 WHERE custom_name = 'Bathing Soap Lavender (Pkt of 4)';
UPDATE shop_products SET display_order = 567 WHERE custom_name = 'Talcum Powder Rose Fragrance 200g';
UPDATE shop_products SET display_order = 568 WHERE custom_name = 'Face Wash Oil Control 100ml';
UPDATE shop_products SET display_order = 569 WHERE custom_name = 'Face Scrub Apricot 100g';
UPDATE shop_products SET display_order = 570 WHERE custom_name = 'Acne Clear Face Wash 100ml';
UPDATE shop_products SET display_order = 571 WHERE custom_name = 'Charcoal Face Mask Peel-Off 50g';
UPDATE shop_products SET display_order = 572 WHERE custom_name = 'Anti-Dandruff Shampoo 400ml';
UPDATE shop_products SET display_order = 573 WHERE custom_name = 'Hairfall Control Shampoo 1L Refill';
UPDATE shop_products SET display_order = 574 WHERE custom_name = 'Herbal Shampoo Daily Care 200ml';
UPDATE shop_products SET display_order = 575 WHERE custom_name = 'Silk & Shine Conditioner 180ml';
UPDATE shop_products SET display_order = 576 WHERE custom_name = 'Sesame Oil for Hair 200ml';
UPDATE shop_products SET display_order = 577 WHERE custom_name = 'Coconut Hair Oil Non-Sticky 300ml';
UPDATE shop_products SET display_order = 578 WHERE custom_name = 'Hair Dye Black Natural';
UPDATE shop_products SET display_order = 579 WHERE custom_name = 'Hair Serum Anti-Frizz 50ml';
UPDATE shop_products SET display_order = 580 WHERE custom_name = 'Hair Spray Strong Hold 100ml';
UPDATE shop_products SET display_order = 581 WHERE custom_name = 'Deep Conditioning Hair Mask 200g';
UPDATE shop_products SET display_order = 582 WHERE custom_name = 'Hair Oil Ayurvedic Blend 300ml';
UPDATE shop_products SET display_order = 583 WHERE custom_name = 'Anti-Hairfall Conditioner 180ml';
UPDATE shop_products SET display_order = 584 WHERE custom_name = 'Shampoo 500ml Bottle';
UPDATE shop_products SET display_order = 585 WHERE custom_name = 'Men''s Shaving Cream Lemon Fresh 70g';
UPDATE shop_products SET display_order = 586 WHERE custom_name = 'Disposable Razor (Pkt of 5)';
UPDATE shop_products SET display_order = 587 WHERE custom_name = 'After Shave Lotion 100ml';
UPDATE shop_products SET display_order = 588 WHERE custom_name = 'Hair Gel Strong Hold 100g';
UPDATE shop_products SET display_order = 589 WHERE custom_name = 'Fairness Cream Men SPF 20 50g';
UPDATE shop_products SET display_order = 590 WHERE custom_name = 'Shaving Foam Sensitive Skin 200g';
UPDATE shop_products SET display_order = 591 WHERE custom_name = 'Cool Mint Toothpaste 150g';
UPDATE shop_products SET display_order = 592 WHERE custom_name = 'Herbal Toothpaste Clove & Salt 100g';
UPDATE shop_products SET display_order = 593 WHERE custom_name = 'Toothbrush Medium Bristle (Pkt of 2)';
UPDATE shop_products SET display_order = 594 WHERE custom_name = 'Mouthwash Mint Fresh 100ml';
UPDATE shop_products SET display_order = 595 WHERE custom_name = 'Dental Floss Mint Flavor';
UPDATE shop_products SET display_order = 596 WHERE custom_name = 'Toothpaste Sensitive Teeth 100g';
UPDATE shop_products SET display_order = 597 WHERE custom_name = 'Electric Toothbrush Refill (2 Heads)';
UPDATE shop_products SET display_order = 598 WHERE custom_name = 'Toothbrush Soft Bristle (Pkt of 2)';
UPDATE shop_products SET display_order = 599 WHERE custom_name = 'Petroleum Jelly 100ml';
UPDATE shop_products SET display_order = 600 WHERE custom_name = 'Fairness Cream SPF15 50g';
UPDATE shop_products SET display_order = 601 WHERE custom_name = 'Cocoa Butter Moisturizing Lotion 400ml';
UPDATE shop_products SET display_order = 602 WHERE custom_name = 'Body Lotion Summer Cool 400ml';
UPDATE shop_products SET display_order = 603 WHERE custom_name = 'Sunscreen Lotion SPF 30 50ml';
UPDATE shop_products SET display_order = 604 WHERE custom_name = 'Lip Balm Strawberry SPF 15';
UPDATE shop_products SET display_order = 605 WHERE custom_name = 'Foot Cream Crack Heel Repair 50g';
UPDATE shop_products SET display_order = 606 WHERE custom_name = 'Moisturizing Cream for Dry Skin 100g';
UPDATE shop_products SET display_order = 607 WHERE custom_name = 'Cold Cream Winter Protection 100g';
UPDATE shop_products SET display_order = 608 WHERE custom_name = 'Toilet Cleaner Power Action 1L';
UPDATE shop_products SET display_order = 609 WHERE custom_name = 'Floor Cleaner Lavender 1L';
UPDATE shop_products SET display_order = 610 WHERE custom_name = 'Glass Cleaner Spray 500ml';
UPDATE shop_products SET display_order = 611 WHERE custom_name = 'Garbage Bags Medium (20 Pcs)';
UPDATE shop_products SET display_order = 612 WHERE custom_name = 'All-Purpose Cleaning Wipes (30 Pcs)';
UPDATE shop_products SET display_order = 613 WHERE custom_name = 'Sink & Drain Cleaner Powder 100g';
UPDATE shop_products SET display_order = 614 WHERE custom_name = 'Air Freshener Spray Jasmine 200ml';
UPDATE shop_products SET display_order = 615 WHERE custom_name = 'Cleaning Scrub Pad (Pkt of 3)';
UPDATE shop_products SET display_order = 616 WHERE custom_name = 'Toilet Brush & Holder Set';
UPDATE shop_products SET display_order = 617 WHERE custom_name = 'Car Polish Liquid 200ml';
UPDATE shop_products SET display_order = 618 WHERE custom_name = 'Rubber Hand Gloves Medium';
UPDATE shop_products SET display_order = 619 WHERE custom_name = 'White Cotton Cloth (Mop Cloth)';
UPDATE shop_products SET display_order = 620 WHERE custom_name = 'Drain Pipe Opener Liquid 500ml';
UPDATE shop_products SET display_order = 621 WHERE custom_name = 'Microfiber Cloth (Pkt of 2)';
UPDATE shop_products SET display_order = 622 WHERE custom_name = 'Air Freshener Gel Can Lavender';
UPDATE shop_products SET display_order = 623 WHERE custom_name = 'Toilet Cleaner Neem Herbal 500ml';
UPDATE shop_products SET display_order = 624 WHERE custom_name = 'Multipurpose Cleaner Spray Citrus 500ml';
UPDATE shop_products SET display_order = 625 WHERE custom_name = 'Toilet Seat Cleaner Spray 200ml';
UPDATE shop_products SET display_order = 626 WHERE custom_name = 'Mop Stick with Refill';
UPDATE shop_products SET display_order = 627 WHERE custom_name = 'Floor Cleaner Pine Fragrance 500ml';
UPDATE shop_products SET display_order = 628 WHERE custom_name = 'Glass Cleaner Refill Pouch 500ml';
UPDATE shop_products SET display_order = 629 WHERE custom_name = 'Plastic Dustbin Medium';
UPDATE shop_products SET display_order = 630 WHERE custom_name = 'Dishwash Liquid Lemon 500ml Bottle';
UPDATE shop_products SET display_order = 631 WHERE custom_name = 'Dishwash Bar 250g';
UPDATE shop_products SET display_order = 632 WHERE custom_name = 'Hand Dishwash Liquid Refill 1L';
UPDATE shop_products SET display_order = 633 WHERE custom_name = 'Steel Scrubber (Pkt of 2)';
UPDATE shop_products SET display_order = 634 WHERE custom_name = 'Dishwash Gel Power Clean 1L';
UPDATE shop_products SET display_order = 635 WHERE custom_name = 'Dishwash Bar XL Size 500g';
UPDATE shop_products SET display_order = 636 WHERE custom_name = 'Kitchen Towel Roll (2 Ply)';
UPDATE shop_products SET display_order = 637 WHERE custom_name = 'Aluminium Foil 10 Meters';
UPDATE shop_products SET display_order = 638 WHERE custom_name = 'Bamboo Skewers (Pkt of 50)';
UPDATE shop_products SET display_order = 639 WHERE custom_name = 'Aluminium Cooking Pot Medium';
UPDATE shop_products SET display_order = 640 WHERE custom_name = 'Serving Spoon Stainless Steel';
UPDATE shop_products SET display_order = 641 WHERE custom_name = 'Non-stick Frying Pan Medium';
UPDATE shop_products SET display_order = 642 WHERE custom_name = 'Kitchen Knife Set (Pkt of 3)';
UPDATE shop_products SET display_order = 643 WHERE custom_name = 'Kitchen Dishcloth (Pkt of 5)';
UPDATE shop_products SET display_order = 644 WHERE custom_name = 'Detergent Powder Regular Wash 1kg';
UPDATE shop_products SET display_order = 645 WHERE custom_name = 'Detergent Powder Machine Wash 2kg';
UPDATE shop_products SET display_order = 646 WHERE custom_name = 'Detergent Bar Pack of 4';
UPDATE shop_products SET display_order = 647 WHERE custom_name = 'Fabric Conditioner Lily Fragrance 500ml';
UPDATE shop_products SET display_order = 648 WHERE custom_name = 'Liquid Starch for Clothes 200ml';
UPDATE shop_products SET display_order = 649 WHERE custom_name = 'Liquid Detergent Front Load 1L';
UPDATE shop_products SET display_order = 650 WHERE custom_name = 'Bleaching Powder 200g';
UPDATE shop_products SET display_order = 651 WHERE custom_name = 'Liquid Blue for White Clothes 100ml';
UPDATE shop_products SET display_order = 652 WHERE custom_name = 'Liquid Detergent Top Load 2L';
UPDATE shop_products SET display_order = 653 WHERE custom_name = 'Fabric Softener Concentrate 1L';
UPDATE shop_products SET display_order = 654 WHERE custom_name = 'Detergent Powder Regular Wash 5kg';
UPDATE shop_products SET display_order = 655 WHERE custom_name = 'Detergent Powder Machine Wash 5kg';
UPDATE shop_products SET display_order = 656 WHERE custom_name = 'Matchbox Standard (Pack of 10)';
UPDATE shop_products SET display_order = 657 WHERE custom_name = 'Pooja Oil Standard 500ml';
UPDATE shop_products SET display_order = 658 WHERE custom_name = 'Agarbathi (Incense Sticks) Sandal';
UPDATE shop_products SET display_order = 659 WHERE custom_name = 'Battery AA (Pack of 4)';
UPDATE shop_products SET display_order = 660 WHERE custom_name = 'Shoe Polish Black 50g';
UPDATE shop_products SET display_order = 661 WHERE custom_name = 'Edible Camphor (Pachai Karpooram) 25g';
UPDATE shop_products SET display_order = 662 WHERE custom_name = 'Kitchen Lighter Refillable';
UPDATE shop_products SET display_order = 663 WHERE custom_name = 'Candle White (Pkt of 10)';
UPDATE shop_products SET display_order = 664 WHERE custom_name = 'Pooja Bell Brass Small';
UPDATE shop_products SET display_order = 665 WHERE custom_name = 'Camphor Tablets (Pooja Karpooram) 100g';
UPDATE shop_products SET display_order = 666 WHERE custom_name = 'Incense Sticks Rose Fragrance';
UPDATE shop_products SET display_order = 667 WHERE custom_name = 'Baby Diapers Medium (Pkt of 10)';
UPDATE shop_products SET display_order = 668 WHERE custom_name = 'Baby Soap Gentle 75g';
UPDATE shop_products SET display_order = 669 WHERE custom_name = 'Baby Lotion 200ml';
UPDATE shop_products SET display_order = 670 WHERE custom_name = 'Baby Oil Aloe Vera 200ml';
UPDATE shop_products SET display_order = 671 WHERE custom_name = 'Baby Wipes (Pkt of 72)';
UPDATE shop_products SET display_order = 672 WHERE custom_name = 'Antiseptic Liquid 100ml';
UPDATE shop_products SET display_order = 673 WHERE custom_name = 'Hand Wash Liquid Lemon 200ml';
UPDATE shop_products SET display_order = 674 WHERE custom_name = 'Cotton Ear Buds (100 Pcs)';
UPDATE shop_products SET display_order = 675 WHERE custom_name = 'Hand Sanitizer Gel 50ml';
UPDATE shop_products SET display_order = 676 WHERE custom_name = 'Hand Wash Refill Pouch Sandal 500ml';
UPDATE shop_products SET display_order = 677 WHERE custom_name = 'Cotton Wool Roll 100g';
UPDATE shop_products SET display_order = 678 WHERE custom_name = 'Sanitary Pads Regular (Pkt of 7)';
UPDATE shop_products SET display_order = 679 WHERE custom_name = 'Cooking Soda 100g';
UPDATE shop_products SET display_order = 680 WHERE custom_name = 'Desiccated Coconut Powder 100g';
UPDATE shop_products SET display_order = 681 WHERE custom_name = 'Baking Powder 100g';
UPDATE shop_products SET display_order = 682 WHERE custom_name = 'Vanilla Essence 30ml';
UPDATE shop_products SET display_order = 683 WHERE custom_name = 'Yeast Dry 50g';
UPDATE shop_products SET display_order = 684 WHERE custom_name = 'Dry Yeast 100g Pouch';
UPDATE shop_products SET display_order = 685 WHERE custom_name = 'Cooking Soda 500g';
UPDATE shop_products SET display_order = 686 WHERE custom_name = 'Milk Chocolate Bar 40g';
UPDATE shop_products SET display_order = 687 WHERE custom_name = 'Hard Boiled Candy Mango Flavor';
UPDATE shop_products SET display_order = 688 WHERE custom_name = 'Chewing Gum Mint Flavor (Pkt of 5)';
UPDATE shop_products SET display_order = 689 WHERE custom_name = 'Mango Bite Candy';
UPDATE shop_products SET display_order = 690 WHERE custom_name = 'Dried Gooseberry (Nellikai Vathal) 100g';
UPDATE shop_products SET display_order = 691 WHERE custom_name = 'Sambar Onion Vathal 50g';
UPDATE shop_products SET display_order = 692 WHERE custom_name = 'Sambhar Vathal 100g';
UPDATE shop_products SET display_order = 693 WHERE custom_name = 'Dry Coconut Whole (Copra) 200g';
UPDATE shop_products SET display_order = 694 WHERE custom_name = 'Dried Mushroom 50g';
UPDATE shop_products SET display_order = 695 WHERE custom_name = 'Dry Shrimp 100g';
UPDATE shop_products SET display_order = 696 WHERE custom_name = 'Dried Fish (Karuvadu) 100g';
UPDATE shop_products SET display_order = 697 WHERE custom_name = 'Coriander Leaves 1 Bunch';
UPDATE shop_products SET display_order = 698 WHERE custom_name = 'Curry Leaves 1 Bunch';
UPDATE shop_products SET display_order = 699 WHERE custom_name = 'Mint Leaves 1 Bunch';
UPDATE shop_products SET display_order = 700 WHERE custom_name = 'Drumstick Leaves (Murungai Keerai) 1 Bunch';
UPDATE shop_products SET display_order = 701 WHERE custom_name = 'Spinach (Palak Keerai) 1 Bunch';
UPDATE shop_products SET display_order = 702 WHERE custom_name = 'Basil Leaves 1 Bunch';
UPDATE shop_products SET display_order = 703 WHERE custom_name = 'Garlic Fresh Green 1 Bunch';
UPDATE shop_products SET display_order = 704 WHERE custom_name = 'Thyme Fresh 50g';
UPDATE shop_products SET display_order = 705 WHERE custom_name = 'Rosemary Fresh 50g';
UPDATE shop_products SET display_order = 706 WHERE custom_name = 'Methi Leaves (Vendhaya Keerai) 1 Bunch';
UPDATE shop_products SET display_order = 707 WHERE custom_name = 'Ponnanganni Keerai 1 Bunch';
UPDATE shop_products SET display_order = 708 WHERE custom_name = 'Coriander Leaves 2 Bunches';
UPDATE shop_products SET display_order = 709 WHERE custom_name = 'Curry Leaves 2 Bunches';
UPDATE shop_products SET display_order = 710 WHERE custom_name = 'Mosquito Repellent Liquid Refill';
UPDATE shop_products SET display_order = 711 WHERE custom_name = 'Mosquito Repellent Coil (Pkt of 10)';
UPDATE shop_products SET display_order = 712 WHERE custom_name = 'Rat Poison Cake 50g';
UPDATE shop_products SET display_order = 713 WHERE custom_name = 'Mosquito Repellent Liquid 45ml';
UPDATE shop_products SET display_order = 714 WHERE custom_name = 'Peanut Candy (Kadalai Mittai) 100g';
UPDATE shop_products SET display_order = 715 WHERE custom_name = 'Jalebi Instant Mix 200g';
UPDATE shop_products SET display_order = 716 WHERE custom_name = 'Rasgulla Tin 500g';
UPDATE shop_products SET display_order = 717 WHERE custom_name = 'Gulab Jamun Instant Tin 500g';
UPDATE shop_products SET display_order = 718 WHERE custom_name = 'Laddu Boondi 250g';
UPDATE shop_products SET display_order = 719 WHERE custom_name = 'Dry Fruit Laddoo 200g';
UPDATE shop_products SET display_order = 720 WHERE custom_name = 'Milk Cake Indian Sweet 250g';
UPDATE shop_products SET display_order = 721 WHERE custom_name = 'Coconut Burfi 250g';
UPDATE shop_products SET display_order = 722 WHERE custom_name = 'Laddu Motichoor 250g';
