apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: nammaooru
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP   # Internal — Ingress will expose to outside
