-- Add default icons/emojis for all categories
-- These can be replaced with actual uploaded images via the admin interface

UPDATE product_categories SET icon_url = '🥬' WHERE name = 'Vegetables';
UPDATE product_categories SET icon_url = '🍎' WHERE name = 'Fruits';
UPDATE product_categories SET icon_url = '🌰' WHERE name = 'Dry Fruits & Nuts';
UPDATE product_categories SET icon_url = '🥛' WHERE name = 'Milk';
UPDATE product_categories SET icon_url = '🧈' WHERE name = 'Dairy & Curd';
UPDATE product_categories SET icon_url = '🥜' WHERE name = 'Milk Alternatives';
UPDATE product_categories SET icon_url = '🍚' WHERE name = 'Rice';
UPDATE product_categories SET icon_url = '🌾' WHERE name = 'Flours & Sooji';
UPDATE product_categories SET icon_url = '🫘' WHERE name = 'Dals & Pulses';
UPDATE product_categories SET icon_url = '🌾' WHERE name = 'Millets & Grains';
UPDATE product_categories SET icon_url = '🫒' WHERE name = 'Cooking Oils';
UPDATE product_categories SET icon_url = '🌶️' WHERE name = 'Spice Powders';
UPDATE product_categories SET icon_url = '🧂' WHERE name = 'Whole Spices';
UPDATE product_categories SET icon_url = '🧂' WHERE name = 'Salt & Spices';
UPDATE product_categories SET icon_url = '🧄' WHERE name = 'Seasoning & Paste';
UPDATE product_categories SET icon_url = '🥐' WHERE name = 'Bakery & Breads';
UPDATE product_categories SET icon_url = '🥞' WHERE name = 'Breakfast & Staples';
UPDATE product_categories SET icon_url = '☕' WHERE name = 'Coffee & Tea';
UPDATE product_categories SET icon_url = '🍯' WHERE name = 'Sweeteners & Sugar';
UPDATE product_categories SET icon_url = '🧊' WHERE name = 'Frozen & Ready to Eat';
UPDATE product_categories SET icon_url = '🍝' WHERE name = 'Pasta & Noodles';
UPDATE product_categories SET icon_url = '🍲' WHERE name = 'Ready to Cook';
UPDATE product_categories SET icon_url = '🍱' WHERE name = 'Ready to Eat';
UPDATE product_categories SET icon_url = '🍪' WHERE name = 'Biscuits';
UPDATE product_categories SET icon_url = '🥔' WHERE name = 'Chips & Crisps';
UPDATE product_categories SET icon_url = '🥗' WHERE name = 'Health Snacks';
UPDATE product_categories SET icon_url = '🥨' WHERE name = 'Namkeen & Savories';
UPDATE product_categories SET icon_url = '🫓' WHERE name = 'Snacks & Papads';
UPDATE product_categories SET icon_url = '🥤' WHERE name = 'Beverages & Health';
UPDATE product_categories SET icon_url = '🥤' WHERE name = 'Soft Drinks & Soda';
UPDATE product_categories SET icon_url = '🧃' WHERE name = 'Water & Juices';
UPDATE product_categories SET icon_url = '🥜' WHERE name = 'Nuts & Seeds';
UPDATE product_categories SET icon_url = '🥫' WHERE name = 'Pickles & Sauces';
UPDATE product_categories SET icon_url = '🧴' WHERE name = 'Bath & Body';
UPDATE product_categories SET icon_url = '💆' WHERE name = 'Face Care';
UPDATE product_categories SET icon_url = '💇' WHERE name = 'Hair Care';
UPDATE product_categories SET icon_url = '🪒' WHERE name = 'Men''s Grooming';
UPDATE product_categories SET icon_url = '🪥' WHERE name = 'Oral Care';
UPDATE product_categories SET icon_url = '🧴' WHERE name = 'Skin Care';
UPDATE product_categories SET icon_url = '🧹' WHERE name = 'Cleaning & Household';
UPDATE product_categories SET icon_url = '🧽' WHERE name = 'Dishwashing';
UPDATE product_categories SET icon_url = '🍽️' WHERE name = 'Kitchen & Dining';
UPDATE product_categories SET icon_url = '🧺' WHERE name = 'Laundry & Fabric';
UPDATE product_categories SET icon_url = '🪔' WHERE name = 'Pooja & Household';
UPDATE product_categories SET icon_url = '👶' WHERE name = 'Baby Care';
UPDATE product_categories SET icon_url = '🩹' WHERE name = 'First Aid & Hygiene';
UPDATE product_categories SET icon_url = '🧴' WHERE name = 'Women''s Hygiene';
UPDATE product_categories SET icon_url = '🧁' WHERE name = 'Baking & Cooking';
UPDATE product_categories SET icon_url = '🍬' WHERE name = 'Confectionery';
UPDATE product_categories SET icon_url = '🫚' WHERE name = 'Dried Foods';
UPDATE product_categories SET icon_url = '🌿' WHERE name = 'Herbs & Leaves';
UPDATE product_categories SET icon_url = '🦟' WHERE name = 'Pest Control';
UPDATE product_categories SET icon_url = '🍮' WHERE name = 'Traditional Sweets';
