spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB:shop_management_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8082
  servlet:
    context-path: /

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-jwt-secret-key-change-this-in-production}
  expiration: 86400000

# File upload configuration
file:
  upload:
    path: ${FILE_UPLOAD_PATH:/app/uploads}

# Application specific configuration
app:
  upload:
    dir: ${APP_UPLOAD_DIR:/app/uploads}
    documents:
      shop:
        path: ${DOCUMENT_UPLOAD_PATH:uploads/documents/shops}
    product-images: ${PRODUCT_IMAGES_PATH:products}
    max-file-size: 10MB

# Logging configuration
logging:
  level:
    com.shopmanagement: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized