server:
  port: 8082
  ssl:
    enabled: false  # SSL will be handled by reverse proxy (nginx)
  forward-headers-strategy: framework

spring:
  application:
    name: shop-management-system
  
  datasource:
    url: ${DB_URL:jdbc:postgresql://your-postgres-host:5432/shop_management_db}
    username: ${DB_USERNAME:your_db_username}
    password: ${DB_PASSWORD:your_db_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
    
  jpa:
    hibernate:
      ddl-auto: validate  # Use validate in production
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        jdbc:
          time_zone: UTC
          batch_size: 20
        order_inserts: true
        order_updates: true
    open-in-view: false
  
  sql:
    init:
      mode: never
      continue-on-error: false
    
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      
  # Email Configuration - Hostinger SMTP
  mail:
    host: ${MAIL_HOST:smtp.hostinger.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:noreplay@nammaoorudelivary.in}
    password: ${MAIL_PASSWORD:noreplaynammaooruDelivary@2025}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    com.shopmanagement: WARN
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/shop-management.log
    max-size: 10MB
    max-history: 30

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your_production_jwt_secret_key_must_be_at_least_256_bits}
  expiration: 86400000 # 24 hours

# File Upload Configuration
file:
  upload:
    path: ${FILE_UPLOAD_PATH:/var/www/shop-management/uploads}
    max-size: 10485760
    allowed-extensions: jpg,jpeg,png,gif,webp

# Application specific upload configuration
app:
  upload:
    dir: ${APP_UPLOAD_DIR:/var/www/shop-management/uploads}
    documents:
      path: ${DOCUMENT_UPLOAD_PATH:/var/www/shop-management/uploads/documents/shops}
    product-images: ${PRODUCT_IMAGES_PATH:/var/www/shop-management/uploads/products}
    max-file-size: 10MB
    allowed-types: pdf,jpg,jpeg,png,docx,doc
  frontend:
    base-url: ${FRONTEND_BASE_URL:https://nammaoorudelivary.in}
    auth:
      login-url: ${FRONTEND_LOGIN_URL:${app.frontend.base-url}/auth/login}
      reset-password-url: ${FRONTEND_RESET_PASSWORD_URL:${app.frontend.base-url}/auth/reset-password}
    shop-owner:
      dashboard-url: ${SHOP_OWNER_DASHBOARD_URL:${app.frontend.base-url}/shop-owner}
    urls:
      shops: ${SHOPS_URL:${app.frontend.base-url}/shops}
      contact: ${CONTACT_URL:${app.frontend.base-url}/contact}
      unsubscribe: ${UNSUBSCRIBE_URL:${app.frontend.base-url}/unsubscribe}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:https://nammaoorudelivary.in,https://www.nammaoorudelivary.in}
    allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}
    allowed-headers: ${CORS_ALLOWED_HEADERS:*}
    allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}

# Shop Module Configuration
shop:
  default:
    page-size: 20
    max-page-size: 100
  validation:
    name:
      min-length: 2
      max-length: 255
    description:
      max-length: 2000

# Email Configuration
email:
  from: ${EMAIL_FROM_ADDRESS:noreply@nammaoorudelivary.in}
  from-name: ${EMAIL_FROM_NAME:NammaOoru Delivery}
  templates:
    welcome: welcome-shop-owner
    password-reset: password-reset
    shop-approval: shop-approval
  subject:
    welcome: "Welcome to NammaOoru - Your Shop Account is Ready!"
    password-reset: "Reset Your NammaOoru Account Password"
    shop-approval: "Your Shop has been Approved!"